### ISSUE TITLE
Request for Training Algorithm Collaboration

### ISSUE THREAD

**Issue by hwanython** [Zhack47/HaNSeg-QuantIF#1]
Dear Zhack47

I hope this message finds you well. I am reaching out to express my keen interest in the training algorithm you have developed for medical imaging. Having dedicated significant time to studying this field, I am deeply impressed by the advancements that your work represents in medical technology.

If possible, I would be honored to learn more about your algorithm and discuss potential collaborations. Sharing knowledge in this area not only broadens our understanding but also enhances our collective ability to make meaningful contributions to healthcare.

Thank you for considering my request. I look forward to the opportunity of working together and contributing to this exciting field.

Warm regards,

**Comment by Zhack47** [comment]
Hello @hwanython, thank you for your interest in this work
As you might know the results are not out yet for HanSeg2023, however once they'll be announced I'll be happy to give you the short paper describing the method I used.
Don't hesitate to ask me any question you have, I can answer them in the mean time.

Have a nice day

**Comment by hwanython** [comment]
Dear @Zhack47 

I hope this message finds you well. Thank you for your exceptional work on the project!

I have a few questions regarding the training process that I hope you could help clarify.

**Registration Process:**
I have been analyzing the process code for affine transformation using ANTs (https://github.com/ANTsX/ANTs), where the CT image is fixed, and the MRI image is moved. After applying the algorithm, I noticed that the MRI voxel values changed significantly, with the minimum value shifting from 32768 to 0. This seems to suggest a potential interpolation issue. Could you share your insights on whether this could affect the training outcomes?

**Preprocessing Steps:**
During your training, did you implement any preprocessing methods, such as clipping, to manage these changes in voxel values?

**Training Schema:**
Are the input images structured to include two channels, one for CT and one for MRI, as part of the training schema?
Thank you for considering my inquiries. I am eager to further our collaboration and contribute to this exciting field. I look forward to your valuable feedback.

Warm regards,

**Comment by Zhack47** [comment]
Regarding the voxel values changes during registration, it would be interesting to localize the zeroes you get  after performing the registration. If they are located at the border of the image, it is likely caused by the padding value being zero, so when the MRI is moved an 'out-of-image' part is moved onto the ct, and this part is filled with 0.
See [this issue](https://github.com/ANTsX/ANTsPy/issues/95) and the [docs](https://antspy.readthedocs.io/en/latest/registration.html). Thank you for pointing this out, this is of major importance since ZNormalization is then applied to the MRI volume

I will issue a fix for that soon
This answers your second point , I only used nnUNet's default preprocessing, so no this issue wasn't addressed.

As for the training scheme, yes, this is how it works. I will try to make this clearer in the code.
Again thank you for pointing this out.

Best

**Comment by Zhack47** [comment]
This should be better now, by setting the default value to `image_mrt1.min()`

**Comment by hwanython** [comment]
Thank you so much! You are great master for me :)
