### ISSUE TITLE
Request for Guidance on Setting Up HaN Dataset with nnU-Net and Replacing ST-Unet

### ISSUE THREAD

**Issue by hwanython** [Zhack47/HaNSeg-QuantIF#2]
Hello [Zhack47](https://github.com/Zhack47),

Firstly, I want to congratulate you on placing 3rd in the challenge! Your success is inspiring, and it has motivated me to explore the nnU-Net framework further.

I am particularly interested in applying nnU-Net to the Head and Neck (HaN) dataset. Could you provide some guidance on how to set up the dataset specifically for nnU-Net? Any details on preprocessing or configuration adjustments would be incredibly helpful.

Additionally, I'm exploring the possibility of replacing the ST-Unet with nnU-Net in my workflow. If you have any guidance or documentation on how to proceed with this replacement, it would be greatly appreciated. However, I understand if this is beyond the scope of what you can provide.

If you're open to further discussion, I would also appreciate the opportunity to communicate via email(hwanython@gmail.com). It could be a great way to deepen my understanding and collaboration on this topic.

Thank you for your time and assistance.

Best regards,

**Comment by hwanython** [comment]
Adding questions!! 

1. could you suffer "Segmentation fault (core dumped)" issue when you train . I did nnUNetv2_train 988 3d_fullres 0 --npz. I got it...
2. Could you let me know your computer spec.? GPU and Mem.

**Comment by Zhack47** [comment]
Sorry I hadn't noticed this issue was open

For the nnUNet dataset format, i forward you to [this page](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md)

The STU-Net is from [uni-medical](https://github.com/uni-medical/STU-Net), you can use the default networks from nnUNet directly. However this is part of the training process, so no modification in this part of the code (inference) is needed once you have a trained  model

**Comment by hwanython** [comment]
I got it! I made it thank to you!
